### ISSUE TITLE
Edit name to fit on iPhone display

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#102]
Per Alex:

Design Studio is the only app on my iPhone hay displays as Design Stu... for title under icon. My guess is most app devs were conscious of the length of the title. Should revisit on next release. 

If it's just Design Studio it may fit. Worth testing and researching. Thanks.

**Comment by younglisa** [comment]
Per Alex would like to go with: Design Studio

@kperusko is this an easy fix? Is it something we could potentially fit into the current sprint?

**Comment by kperusko** [comment]
@younglisa title usually gets truncated after 10-12 characters, depending on the width of each character. So even the shorter name may get truncated. We have to just try and see what will happen. 
We'll also need to check with @sshaar08 to see renaming the app will have some implications on review/publish process.

**Comment by brooklynchuck** [comment]
If you omit the space, DesignStudio is 12 characters.

On Tue, Jan 12, 2016 at 7:04 AM -0800, "Kristijan Perusko" <notifications@github.com<mailto:notifications@github.com>> wrote:

@younglisahttps://github.com/younglisa title usually gets truncated after 10-12 characters, depending on the width of each character. So even the shorter name may get truncated. We have to just try and see what will happen.
We'll also need to check with @sshaar08https://github.com/sshaar08 to see renaming the app will have some implications on review/publish process.

##

**Comment by sshaar08** [comment]
Verified

**Comment by sshaar08** [comment]
@younglisa still the same name in the app store right we are not changing?

**Comment by younglisa** [comment]
@sshaar08 what are the implications of having it changed in the app store also?

**Comment by sshaar08** [comment]
lose unique listings when search but might make it easier to search for. @kperusko  @brooklynchuck @Misokate we should all speak for a sec on this one
