### ISSUE TITLE
Replace Sammy's email for the App support email

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#104]
Josh created an app support email so we can replace Sammy's email.

appsupport@alexanderinteractive.com

This exists:
Within the app under "Contact Us" (see settings)
App Store Application

@sshaar08 am I missing any other location?

**Comment by sshaar08** [comment]
who is checking or has access to this email @younglisa @kperusko

**Comment by younglisa** [comment]
@sshaar08 just me and you I believe
