### ISSUE TITLE
Template Screen :: Adjust deleting action to be right to left

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#106]
Per User Testing: Deleting design studios goes from left to right. Instead of right to left like most apps. Would want to change this to prevent accidents.

**Comment by kperusko** [comment]
@younglisa @sshaar08 we had left to right deleting, but I guess they wanted right to left swipe action :) Switched the desc. and title to match what I've done.

**Comment by sshaar08** [comment]
working
