### ISSUE TITLE
Timer Page

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#11]
PTI 009

https://aiaio.invisionapp.com/share/424VSP4YP#/screens/114871385

Components:
- Timer 
- Activities 
- Challenges
- Objectives

**Comment by sshaar08** [comment]
https://invis.io/2U528PVBA
https://invis.io/ZT528QIFQ
https://invis.io/NP528QRWR

**Comment by younglisa** [comment]
To summarize from today:

App closes:

> Phone dies / app is fully exited -- inprogress studio becomes fully disabled (for MVP). User will need to copy over and start a new one
> App goes out of focus but still runs -- timer continues with a push notification when the activity timer is up

When Studio is done:

> Everything is read-only EXCEPT presenter notes
> Presenter notes are editable by going back to each activity to update

When going back to activities during the studio:

> Back button to have a "List" label to make it clear you are always going back to list view
> Begin Studio button changes to timer indicator

Let me know of any misalignment @Misokate @kperusko @sshaar08
