### ISSUE TITLE
Time's up screen doesn't show on time if the phone gets locked

### ISSUE THREAD

**Issue by kperusko** [aiaio/DesignStudioExpress#110]
Steps to reproduce:
1. Start an activity
2. Lock the screen for 30 sec
3. Unlock the screen and wait for the timer to get to 0:00
4. Time's up will show after X seconds of delay  (> 5sec in my testing)

**Comment by kperusko** [comment]
@younglisa I've added this bug that @Misokate found while doing the design studio with the app.
cc @sshaar08

**Comment by sshaar08** [comment]
This one is looking good so far ill close this one last
