### ISSUE TITLE
Challenge screen is appears twice in the navigation stack after finishing design studio

### ISSUE THREAD

**Issue by kperusko** [aiaio/DesignStudioExpress#111]
Steps to reproduce:
1. Create a new Design studio
2. Add 1 challenge with 1 activity that has 1 min duration
3. Wait for the Time's up screen
4. Click on "Next activity" button"
5. When Gallery screen shows, click on the back button
6. Challenges screen will appear. Click on back button again and Challenges screen will appear again, but Detail design studio screen should appear instead.

**Comment by sshaar08** [comment]
working well for me
