### ISSUE TITLE
Post Studio :: Send Photos

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#13]
PTI 010

Function to send photos captured post-studio

**Comment by sshaar08** [comment]
@younglisa  do we want a place holder page in the app for send photos

**Comment by younglisa** [comment]
@sshaar08 yes it's this flow:

https://aiaio.invisionapp.com/d/main/#/console/5342955/117207205/preview#project_console

https://aiaio.invisionapp.com/d/main/#/console/5342955/117207203/preview#project_console

https://aiaio.invisionapp.com/d/main/#/console/5342955/117207204/preview#project_console

**Comment by younglisa** [comment]
Per discussion we will leverage native iOS functionality and user will share photos via their camera app as they would any other photos.

Note there will be a separate album that automatically populates photos taken within the studio from which a user can see / share.

@Misokate @sshaar08 @kperusko let me know of any misalignment there.
