### ISSUE TITLE
Post Studio :: Gallery

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#14]
PTI 011

Gallery view of photos

**Comment by sshaar08** [comment]
https://invis.io/EW528OEXP

**Comment by sshaar08** [comment]
https://github.com/zhangao0086/DKImagePickerController

**Comment by younglisa** [comment]
See attached for decisions per discussion today.

Sharing photos discussed in #13 

@Misokate @sshaar08 @kperusko let me know of any misalignment

@brooklynchuck per discussion on Invisionapp will need tweaked copy for this screen per the updated flow
![2015-12-11_1342](https://cloud.githubusercontent.com/assets/15143346/11752557/4722e0fc-a00e-11e5-8b92-5d3d336808fd.png)

**Comment by brooklynchuck** [comment]
Question: the top copy that says "Design Studio Name" is just a placeholder, right? 

Here's the "encouraging" copy: 
"Photograph your groups’ results now to automatically save them with this studio template. Share the brilliance. Take a bow."

I believe the album name that all photos will be saved to should be something like:

"[Template Name] DSX photos"

C:

**Comment by younglisa** [comment]
@brooklynchuck thanks! The one snag is the photo album can't dynamically pull in the template name. Would just "DSX photos" be ok as a general album name?

**Comment by brooklynchuck** [comment]
Can we put the date in the album name? That would be helpful, as many times on a phone, you don't see the date something was created without getting deeper into it. 

But otherwise, yes, "DSX Photos ##/##/####" or just "DSX Photos". 

C:

**Comment by younglisa** [comment]
@brooklynchuck we can only have one album for all dsx photos (similarly to how Instagram just pools all photos in one). So thinking we'll need to go with "DSX Photos"

cc: @kperusko @Misokate
