### ISSUE TITLE
Share / Rate App

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#16]

**Comment by younglisa** [comment]
Part of the settings page

**Comment by younglisa** [comment]
#17

**Comment by sshaar08** [comment]
@younglisa do we have a page for this in the prototype

**Comment by younglisa** [comment]
@sshaar08 Here: https://aiaio.invisionapp.com/d/main/#/console/5342955/117207235/preview

@kperusko @Misokate @brooklynchuck were we thinking Share this app would link off to another page?

**Comment by brooklynchuck** [comment]
I thought it would open a pull down listof sharing options: facebook, linkedin, twitter, and then you choose one of those and it opens the api and generates a post. (which would mean, we need to write the copy to pre-populate that post for each sharing service).

at least that's what I was thinking. anyone else thinking that?

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com

**Comment by younglisa** [comment]
@Misokate @kperusko per Chuck's comment -- agree / disagree? Think that makes sense to me; is there a common iOS practice / native functionality we could potentially leverage here?

cc: @brooklynchuck @sshaar08

**Comment by Misokate** [comment]
@younglisa @brooklynchuck  Agreed. It should be on the settings page in that "Share this App" area, but @kperusko had said that the pull down functionality is not native to ios apps, so I had it as another page, (the example styling is the example settings page). Once we figure out the content and which we want to highlight on that page I can design around it!

**Comment by brooklynchuck** [comment]
when might we need copy for the actual pre-populated posts (FB, LI, Tw)? Hopefully after Thanksgiving.

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com

**Comment by younglisa** [comment]
@brooklynchuck -- yes lets target this for the week we're back

@Misokate @kperusko let's make the assumption we're doing FB, LI, TW sharing. If that presents any technical or design challenges up front let me know

**Comment by younglisa** [comment]
Share copy is here: https://basecamp.com/2380615/projects/10699840/todos/221222678#comment_364312748

I've made a separate ticket for myself to make the by.ai/dsx link when that is ready.

Per Christina's comment, will separate out Twitter to see if we can fit this in during QA.

**Comment by timbroder** [comment]
Hi all,

Rating and reviewing the app jumps straight to the review tab of the app in the App Store. The id for this is already pulled in from iTunes Connect and will **not** have to be updated.

We **can** have different text for certain sharing activities.

Some have a subject, a message, and an icon. To see wht has what, and the full list of sharing actifivites we can test for to have special text (everything else falls to generic), please see the table halfway down this page: http://nshipster.com/uiactivityviewcontroller/

People can have a lot of different apps that can share installed (see screenshot from my phone), so we should have good generic text. 

![img_1132](https://cloud.githubusercontent.com/assets/121503/11747641/658231a4-9ff2-11e5-85fb-da3339e6e4ec.PNG)

@kperusko The code for this is broken out on it's own here: https://github.com/aiaio/DesignStudioExpress/blob/85bba266bf47f396190334f75bda6cb06cb8b44c/DesignStudioExpress/ViewModels/DesignStudioAtivityItemSource.swift
@brooklynchuck you should also peek at that file to see what we have to work with text wise
@Misokate WE CAN ADD ICONS
