### ISSUE TITLE
Load Screen :: Input Final Video 

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#19]
https://invis.io/Y6516DRUP

Per standup, we have an FPO video in for now but will need to finalize this for launch

**Comment by sshaar08** [comment]
https://aiaio.invisionapp.com/share/424VSP4YP#/screens/115435036

**Comment by kperusko** [comment]
Added final version of the video (study05.mov) that has ~40mb. If that ends up being too large we can replace it with study06.mov that's ~7mb.
