### ISSUE TITLE
Fix the height of the image for different devices on My Design Studio (Home) screen

### ISSUE THREAD

**Issue by kperusko** [aiaio/DesignStudioExpress#23]
Based on the feedback from our first demo, we should fix the height of the image on My Design Studio (Home) screen. When the screen is initially loaded, the last visible cell should be always a small line (~10 points), to indicate that there are more cells in the bottom (i.e. that the view is scrollable).

Related to #3

**Comment by sshaar08** [comment]
This is completed and on
