### ISSUE TITLE
Challenge description on the Challenge details screen is not readable

### ISSUE THREAD

**Issue by kperusko** [aiaio/DesignStudioExpress#29]
Francia said that the challenge description text is not very readable. She suggested that we change the font size (or font color) to make it more readable. Kate advised that we can't make the font color lighter (and we can't use white, because that's the same as the color for the actual text, which will probably be confusing).

**Comment by younglisa** [comment]
If it's color it would be white

@Misokate to advise on what font change would be if it were to be updated. Wouldn't work from iPhone 5

Only applies to placeholder text
