### ISSUE TITLE
Allow Push Notifications

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#33]
Will need to allow push notifications for when a user puts app out of focus but it still runs (see ticket 11)

cc: @sshaar08 @kperusko

**Comment by kperusko** [comment]
Added local notifications with default sound (push notifications are used when we want to send remote notifications).

**Comment by kperusko** [comment]
@younglisa , @brooklynchuck Notification body is currently 
"[Activity name] is finished". Do we want to to show something different?
