### ISSUE TITLE
Add CTA to copy studio

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#34]
Will need to add CTA to be able to copy studio upfront to take as a template -- would apply to all studios (Ai templates, user-created studios)

Decision is that ai templates are uneditable directly and will need to be copied to edit

Applies: https://aiaio.invisionapp.com/d/main/#/console/5342955/117207105/preview

Let me know of any misalignment @Misokate @kperusko @sshaar08

**Comment by sshaar08** [comment]
lock the templates and remove the studio finished button boom!

**Comment by kperusko** [comment]
@sshaar08 Opened a new ticket for locking templates #78
