### ISSUE TITLE
Timer Screen -- Skip to next activity Bar at the bottom -- Add arrow icon -- Update font styles

### ISSUE THREAD

**Issue by Misokate** [aiaio/DesignStudioExpress#44]
Add arrow icon (per designs) to the right 

Update font styles--

Skip to:
Avenir Heavy:
Font-size: 12pt
Letter-spacing: 1.85
Text-transform: Uppercase

Activity name:
Avenir Light:
Font-size: 12pt
Letter-spacing: 1.85
Text-transform: Uppercase

Should look like this: ![skip to --](https://cloud.githubusercontent.com/assets/15143350/11641480/721dedf2-9d06-11e5-9cf7-160b83645cff.png)

**Comment by younglisa** [comment]
Completed
