### ISSUE TITLE
Add Twitter Share

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#50]
If we have time left over lets see if we can add in Twitter sharing (per Christina's suggestion)

**Comment by kperusko** [comment]
User has to have Twitter app installed and be logged in the Twitter app and the Twitter share will be enabled.

// @younglisa, @sshaar08

**Comment by brooklynchuck** [comment]
Did we create a text version of the share message?

**Comment by kperusko** [comment]
Share message is "DesignStudioExpress guides teams through timed rounds of brainstorming to solve design challenges fast! @aiaio #DSX http://by.ai/dsx"

@brooklynchuck , @younglisa , @sshaar08

**Comment by brooklynchuck** [comment]
that's brilliant

**Comment by kperusko** [comment]
@brooklynchuck I think you wrote it :)

// @sshaar08, @younglisa

**Comment by sshaar08** [comment]
verified
