### ISSUE TITLE
Replace the templates.pdf with real PDF

### ISSUE THREAD

**Issue by kperusko** [aiaio/DesignStudioExpress#52]
We have a placeholder PDF that will be downloaded when clicking "Download Sketching Templates". Replace it with real document.

**Comment by Misokate** [comment]
@younglisa Do you know where I can find the templates that we use for design studios? I was thinking of adding in the design studio logo :)

**Comment by younglisa** [comment]
@Misokate you can find them here: https://hamster.tools/pages/viewpage.action?spaceKey=UXandDesign&title=12+-+Design+Studios
