### ISSUE TITLE
FAQ / Guide

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#6]
https://invis.io/W3528U2NZ

PTI 003

Components
- Materials List
- Help Articles

**Comment by younglisa** [comment]
@sshaar08 @kperusko @Misokate FYI I spoke to Andrew about folding in a Fender for this and should be good to use Tony. When we are ready with designs lets fold him in.

**Comment by younglisa** [comment]
@camachowebworld @kperusko is this in the latest build that I can pull from crashlytics? I can't seem to get at it

**Comment by younglisa** [comment]
Typos corrected for this, requires Josh R. to finish it off.

@kperusko let me know the ticket you have in with Josh and I can followup

**Comment by younglisa** [comment]
@Misokate -- @kperusko updated the build with the latest on this. Per discussion with him / Tim afterwards, thinking the attached could be an option. Thoughts?

Kristijan -- correct me if we're misaligned there.
![2015-12-11_1233](https://cloud.githubusercontent.com/assets/15143346/11750974/8208e9f0-a004-11e5-9d56-dacdf57ca17d.png)

**Comment by Misokate** [comment]
@younglisa @kperusko This sounds great to me! How would we all feel about having an X at the top right that functions like a dismiss?

**Comment by kperusko** [comment]
@younglisa @Misokate that would work.

**Comment by younglisa** [comment]
Great thanks guys

**Comment by kperusko** [comment]
Ok I've made the changes. I'll need some guidance from @Misokate on how to style the dismiss/back button.

**Comment by Misokate** [comment]
@kperusko Do you mind sending me a screen shot? I was thinking just an X out at the top right of the screen that brings you back to the home screen. What do you think?
