### ISSUE TITLE
Editing Studio :: Add lock icon to text that is locked from editing

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#70]
This ticket is to denote we will need to add a lock icon where text is no longer editable

**Comment by younglisa** [comment]
Assigned to @Misokate to provide the lock icon.

Please reassign to @kperusko when ready.

@kperusko to evaluate feasibility to add this in or if there is an easier route.

cc: @sshaar08

**Comment by sshaar08** [comment]
looking good
