### ISSUE TITLE
Settings :: Update Terms & Conditions with Legalese

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#72]
Need to add some T&Cs to the app -- assigning it to myself to pull it together

**Comment by younglisa** [comment]
@sshaar08 is there a requirement for a privacy policy for the app store? I'm seeing that in researching other apps and if that's the case our legalese probably needs to be on a separate page no?

**Comment by younglisa** [comment]
Posted Legalese here: https://basecamp.com/2380615/projects/10699840/documents/10311597

**Comment by younglisa** [comment]
Per discussion thinking this needs to be a standalone webpage @kperusko

**Comment by sshaar08** [comment]
@younglisa not if we dont collect users data or kids under 13 are our target

**Comment by younglisa** [comment]
@kperusko by.ai link here: http://by.ai/dsxprivacy

Please remove "/Legalese" from the heading so it just says "Privacy Policy"
