### ISSUE TITLE
Rename Template Titles

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#73]
See attachment.

@brooklynchuck let me know if you have any objections to the copy tweak. Feedback was essentially to make it clear these were templates (aside from the color treatment)

@kperusko assigning it to you -- if there are character count issues let me know.
![2015-12-18_1842](https://cloud.githubusercontent.com/assets/15143346/11909639/9b30b3c8-a5b7-11e5-85a4-7f3846afe5a6.png)

**Comment by brooklynchuck** [comment]
Yeah, fine. I'm tempted to say "Template: New Product" instead of concept, but not sure. Thoughts?

**Comment by younglisa** [comment]
I would advocate for it to still say Concept, because the template speaks to sketching and iterating on something that could either be the entire thing (like a customer app) or a piece of it (like quoting)

Thoughts? @kperusko @Misokate 
@brooklynchuck
