### ISSUE TITLE
Settings :: Update "About Ai" text

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#74]
Per demo, feedback to update the "About Ai" text so that it indicated Ai = the makers (since we only have that line in the into)

@brooklynchuck take a look at the attached suggestion and let me know if you feel we need to tweak

@kperusko assigning to you to execute
![2015-12-18_1848](https://cloud.githubusercontent.com/assets/15143346/11909719/c4bd9656-a5b8-11e5-86ca-a76108c54179.png)

**Comment by brooklynchuck** [comment]
About the makers: Ai

Who Made This?

Learn Who Made This

[the logo icon helps name check Ai, right? do we need to repeat? didn't people see who made it when they downloaded it? when they launch the app?]

Thoughts? 

C:

**Comment by younglisa** [comment]
@brooklynchuck per discussion during standup liking this:

Who Made This?

Would have the Ai logo next to it

Thanks!

cc: @kperusko
