### ISSUE TITLE
Post Studio :: Change CTA of finished studio button

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#76]
@Misokate @sshaar08 @brooklynchuck @kperusko 

Logging this ticket as it sounded like we may want to update the text in this CTA. What do we want it to say? See Photos?
![2015-12-18_1907](https://cloud.githubusercontent.com/assets/15143346/11909894/0dc879ea-a5bb-11e5-99a0-ee30961e259b.png)

**Comment by brooklynchuck** [comment]
Right. Replied on Invision. Maybe all this needs is: "Design studios help you get a week's...."

Am I hearing the feedback right? 

C:

**Comment by brooklynchuck** [comment]
ALL DONE. PHOTO TIME
LAUNCH PHOTO GALLERY
PHOTOGRAPH YOUR RESULTS

Any of those three sparking anything? 

C:

**Comment by younglisa** [comment]
@brooklynchuck thanks! In reviewing these options during standup we actually thought it would be good to mash up 1 and 2 as follows:

ALL DONE. LAUNCH GALLERY

Thoughts?

cc: @kperusko @sshaar08 @Misokate

**Comment by brooklynchuck** [comment]
yep

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com
