### ISSUE TITLE
Guide :: Update Headline

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#79]
Per Sprint 4 demo, thought is to tweak headline guide copy to intro what a design studio is. 

Per Chuck, suggested updated headline is: 

Design studios help you get a whole week's work done in a day.
![2015-12-21_1038](https://cloud.githubusercontent.com/assets/15143346/11934313/6ab3fd30-a7cf-11e5-8508-2e9e6d05b096.png)

**Comment by younglisa** [comment]
Reassigned to @sshaar08 per standup. If we need Tony to jump on this let me know.

Please share with @Misokate for design to see if it needs to break to two lines

**Comment by sshaar08** [comment]
pushed
