### ISSUE TITLE
Post Studio :: No photos / no access granted state

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#82]
Need to identify copy for when a user has no photos to populate at the end of the studio / did not allow access to photos

**Comment by younglisa** [comment]
@kperusko FYI in the latest build I allowed push notifications but was not prompted for photo access. Not sure if that's just because it wasn't pushed yet.

**Comment by younglisa** [comment]
![image1 4](https://cloud.githubusercontent.com/assets/15143346/11938713/b323dd36-a7ea-11e5-8323-127b43639852.PNG)

**Comment by younglisa** [comment]
@kperusko to clarify the steps at this point are:

*Allow the app access to photos
*Open camera
*Take photo
*Save to Design Studio Album --> Is this automatically created when there are no photos?

Would like to confirm so the corresponding copy is accurate.

**Comment by kperusko** [comment]
@younglisa you probably already gave the access to the photo gallery, and app will only ask you once (if you uninstall the app, the settings are stored 24h so you'll have to clear privacy settings).

The steps above are accurate, but folder is created only if you start taking pictures from within the app.

**Comment by younglisa** [comment]
@kperusko so if you are at the end of the studio and have not taken any photos, but decide to do it all at the end, those photos will NOT show up in the gallery view because the folder will not have been created?

Feel like that is a potential issue.

**Comment by kperusko** [comment]
@younglisa talked with @sshaar08 and Francia - we're going to create a folder/ask for permissions when they open the app for the first time.

**Comment by younglisa** [comment]
@kperusko that makes sense, thanks! Will think about copy.

**Comment by younglisa** [comment]
What if for this error state we leverage the other message and add a line to denote the additional instructions? @brooklynchuck thoughts?

Header (whatever the current one is think it's:) Oops...no photos!

Body:
Photograph your groups' results now to automatically save them with this studio template. Share the brilliance. Take a bow.

Tip: Be sure to allow the app access to your photos and save them to the Design Studio Express album for easier access.

**Comment by brooklynchuck** [comment]
sorry, i'm not completely understanding the flow on this. that's my fault! Lisa, can I ask you for 5 minutes to explain it to me in person?

C:

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com

**Comment by brooklynchuck** [comment]
IF NO PERMISSION

Header: Photos need your permission!

Body: Open iPhone Settings and tap on Design Studio Express. Allow app to access your photos. Take photos using camera as normal and save in new "DSX Photos" folder.

IF PERMISSION, BUT NO PHOTOS

Header: What? No photos?

Body: You'll want a visual record later to see how you solved your design challenge, or share with the team. Take photos using camera as normal and save in the "DSX Photos" folder.

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com

**Comment by younglisa** [comment]
Thanks @brooklynchuck ! 

@kperusko tossing it over to you
