### ISSUE TITLE
Error States

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#83]
Need confirmed copy for the following error states. Screenshot denotes design treatment:

Error popup when deleting challenges
Title: Warning
Body: Are you sure you want to delete this challenge?

Error popup when trying to delete currently active or finished challenge
Title: Warning
Body: You can't delete currently active or finished challenge!

Error popup when trying to delete an design studio
Title: Warning
Body: Are you sure you want to delete this design studio?

Error popup when trying to delete an active design studio
Title: Warning
Body: You cannot delete currently active design studio!

Error popup when tapping on Contact us (i.e. trying to send an email from the phone), but the Email app wasn't configured, so we can't do anything without that.
Title: Preparing email failed
Body: Please configure your device to send email

Error popup when trying to start design studio, while another studio is running
Title: Warning
Body: [Studio name] design studio is running.

Error popup when trying to start design studio with an invalid state
Title: Warning
Body: You have to have at least one challenge and every challenge has to have at least one activity.
![img_0130](https://cloud.githubusercontent.com/assets/15143346/11944188/3fd59b94-a812-11e5-8b24-9aa6f44ac1cb.PNG)

**Comment by younglisa** [comment]
@brooklynchuck @kperusko tweaked a few so they were more indicative of what the issue is.

Chuck -- let me know your thoughts. If you think some personality is appropriate here, would love to get your take.

Error popup when deleting challenges
Title: Warning
Body: Are you sure you want to delete this challenge?

Error popup when trying to delete currently active or finished challenge
Title: Cannot delete challenge
Body: Finished or currently active challenges cannot be deleted. 

Error popup when trying to delete an design studio
Title: Warning
Body: Are you sure you want to delete this design studio?

Error popup when trying to delete an active design studio
Title: Design Studio in progress
Body: Please skip activities to complete.

Error popup when tapping on Contact us (i.e. trying to send an email from the phone), but the Email app wasn't configured, so we can't do anything without that.
Title: Cannot send an email
Body: Please configure your device to send email

Error popup when trying to start design studio, while another studio is running
Title: Cannot start studio
Body: [Studio name] design studio is already running.

Error popup when trying to start design studio with an invalid state
Title: Design Studio is incomplete
Body: At least one challenge with at least one activity per challenge required.

**Comment by brooklynchuck** [comment]
Just a few tweaks for personality - all welcome to weigh in on whether these tweaks improve or degrade said personality [&#X1f609]

Error popup when deleting challenges
Title: You sure?
Body: Deleting this challenge cannot be undone.

Error popup when trying to delete currently active or finished challenge
Title: Not right now
Body: Active challenges cannot be deleted. Finish this Design Studio first, then you can delete.

Error popup when trying to delete an design studio
Title: You sure?
Body: Deleting this design studio cannot be undone.

Error popup when trying to delete an active design studio
Title: Not right now
Body: This Design Studio is in progress. Skip activities to complete it, then you can delete.

Error popup when tapping on Contact us (i.e. trying to send an email from the phone), but the Email app wasn't configured, so we can't do anything without that.
Title: I'm sorry, Dave. I'm afraid I can't do that.
Body: Please first configure your device to send email.

Error popup when trying to start design studio, while another studio is running
Title: Whoa!
Body: Nice try on multi-tasking, but [Studio name] design studio is already running.

Error popup when trying to start design studio with an invalid state
Title: Whoa!
Body: Your design studio needs at least one challenge (each with at least one activity) before you can start it.

## 

Chuck Wells
Copywriter/CD
646.320.5657
Ai |  alexanderinteractive.com

**Comment by kperusko** [comment]
I like it a lot, especially the HAL 9000 reference :)

Kristijan Perusko
Back End Developer
212.598.2800
Ai | alexanderinteractive.com​

Ai was just named as one of the Best Places to Work by both Ad Agehttp://adage.com/article/news/ad-age-s-places-work-2015/301323/ and Crain’s New Yorkhttp://www.crainsnewyork.com/section/bestplaces/2015#alexander-interactive!

**Comment by younglisa** [comment]
@brooklynchuck love it!
