### ISSUE TITLE
photo taking: Add messaging warning if you do not allow access to camera

### ISSUE THREAD

**Issue by sshaar08** [aiaio/DesignStudioExpress#85]

**Comment by younglisa** [comment]
Per Chuck:

IF NO PERMISSION

Header: Photos need your permission!

Body: Open iPhone Settings and tap on Design Studio Express. Allow app to access your photos. Take photos using camera as normal and save in new "DSX Photos" folder.

Treatment same as #82

**Comment by kperusko** [comment]
@younglisa @brooklynchuck 
I've added this text in the error popup. Let me know if we need to change it. Closing this for now.
title: "Camera needs your permission!"
message: "Open iPhone Settings and tap on Design Studio Express. Allow app to access your camera."
