### ISSUE TITLE
On the Legal Screen -- Needs Orange header bar and  "Acknowledgements" should be White

### ISSUE THREAD

**Issue by Misokate** [aiaio/DesignStudioExpress#88]

**Comment by younglisa** [comment]
@Misokate can you add in a screenshot?

**Comment by Misokate** [comment]
![settings_example](https://cloud.githubusercontent.com/assets/15143350/11967481/2e440752-a8d1-11e5-97f2-37ffc6b1eacf.png)

Template for header attached!
