### ISSUE TITLE
Templates :: Remove "Edit It" when locked

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#92]
Per final demo - need to rethink verbiage on templates as everything is locked.
![2016-01-05_1541](https://cloud.githubusercontent.com/assets/15143346/12127036/d90557bc-b3c2-11e5-974e-f3a3f85ed277.png)

**Comment by brooklynchuck** [comment]
Here are some early thoughts on replacements: 
"LOCKED"
"COPY DESIGN STUDIO TO EDIT"
"TITLE LOCKED"
"UNLOCK TO EDIT" [is the lock icon or "edit it" field tappable?]

Or replace it with nothing. Just keep the lock icon. 

???

C:

**Comment by sshaar08** [comment]
looking good
