### ISSUE TITLE
Update T&Cs

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#93]
Need to update Terms and Conditions within the app with the attached.

NOTE: this is the legalese that exists within the app 
[Terms and Conditions .docx](https://github.com/aiaio/DesignStudioExpress/files/90621/Terms.and.Conditions.docx)

**Comment by sshaar08** [comment]
This is still open we need to change the title to Terms and conditions on the page

**Comment by sshaar08** [comment]
verified on qa
