### ISSUE TITLE
Create Privacy Policy

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#94]
Need a standalone webpage to display Privacy Policy details:

Should have similar formatting to T&Cs 
[Privacy Policy.docx](https://github.com/aiaio/DesignStudioExpress/files/90618/Privacy.Policy.docx)

Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Note: this is to be linked to from the app store instead of FAQs. Added step is to see about changing by.ai/dsxsupport to link to the privacy policy page

**Comment by younglisa** [comment]
@camachowebworld take a look at this one and let me know your thoughts on effort-level. 

Timing -- would need this complete by Tue 2/9

@Misokate I noted the design would be the same as the in-app T&Cs. Is that accurate or is there modifications you would want to fold in for that page?

**Comment by Misokate** [comment]
@younglisa Exactly! Thank you

**Comment by younglisa** [comment]
Per discussion on Slack

(From Kate)
[Francia] and I just met about this we think it makes the most sense to build a page into the Ai website that is only linked to from the App store

that way we’re bringing users into our site and we don’t need to create a design for a one off page.

We could use the same header styles as across the Ai site and have the H1 Design Studio Express and the H2 below: "Privacy Policy."

**Comment by camachowebworld** [comment]
@younglisa this what I have so far.

![image](https://cloud.githubusercontent.com/assets/4406039/12588917/d16c1ea2-c40f-11e5-832a-992ef172fe8d.png)

**Comment by camachowebworld** [comment]
This is without the nav:
![image](https://cloud.githubusercontent.com/assets/4406039/12589683/de83a886-c413-11e5-9a65-ab4083fc8b6c.png)

**Comment by younglisa** [comment]
Thanks @camachowebworld !

@Misokate -- take a look at the above from Tony, thoughts?

@kperusko @sshaar08 should we have meta description / keywords for this page? A part of me thinks we don't want this searchable if it's only in the app but will google ding ai.com for that?

**Comment by kperusko** [comment]
@younglisa we can use noindex to make this not searchable. I'm not sure if google will ding ai.com for that but I did found this link where they are saying that the noindex page will not be indexed but will still accumulate PageRank juice http://webmasters.stackexchange.com/questions/67884/do-noindex-follow-pages-pass-pagerank-link-juice

**Comment by Misokate** [comment]
Awesome @camachowebworld , works perfectly in the Ai site template. Can we add the nav back in without a way back or is that a no no @kperusko  ?

cc/ @sshaar08  @younglisa

**Comment by kperusko** [comment]
@Misokate Since it's a standalone page that's not showing in the app we can have normal Ai navigation. 
// @sshaar08 @younglisa

**Comment by younglisa** [comment]
Aite @camachowebworld can you add back the full nav? Sorry lol

@kperusko is we use noindex so we still need meta description and keywords or can we leave that blank?

**Comment by kperusko** [comment]
@younglisa since it's used only when the page is indexed by the search engine, we can probably leave that out. Firefox and Opera, use meta description as the default description of the page when bookmarked (not sure if anybody will want to bookmark Privacy policy page).

// @sshaar08

**Comment by younglisa** [comment]
Cool thanks @kperusko 

@camachowebworld let's leave it off for now then.

**Comment by camachowebworld** [comment]
@younglisa, @kperusko, @sshaar08, @Misokate 

Dohhh... Sorry, I didn't see these last few comments... I added the primary nav back up top. The work is committed on branch, "dsx-privacy-policy-2016-01".

![image](https://cloud.githubusercontent.com/assets/4406039/12682803/5469af52-c66a-11e5-99cc-b396b7d93b79.png)

**Comment by sshaar08** [comment]
@younglisa does this have to be launched with an ai.com update?

**Comment by younglisa** [comment]
@sshaar08 yep that makes sense. Let's make sure we check in on that next week when we do the ai.com prod push.
