### ISSUE TITLE
Checklist :: Show full checklist

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#95]
@kperusko @Misokate can you verify the correct interaction here? At present it seems like I should either be able to download or expand the full list but neither is possible
![2016-01-11_0955](https://cloud.githubusercontent.com/assets/15143346/12236763/984b4b10-b849-11e5-8a60-527ec1f9489a.png)

**Comment by younglisa** [comment]
Need to:
Update the icon -- present in the drive
Show all text

**Comment by sshaar08** [comment]
Looking good
