### ISSUE TITLE
Settings :: Adjust copy

### ISSUE THREAD

**Issue by younglisa** [aiaio/DesignStudioExpress#96]
Not sure the original copy we had here makes sense as we can't really adjust the sound right @kperusko ?

Does it make sense to still think of this as "Settings"?
![2016-01-11_0956](https://cloud.githubusercontent.com/assets/15143346/12236804/c9663b1a-b849-11e5-98de-9a70af3da232.png)

cc: @brooklynchuck @Misokate

**Comment by brooklynchuck** [comment]
so there's only 4 options here now?

**Comment by younglisa** [comment]
@brooklynchuck no there are links to Legalese as well

**Comment by brooklynchuck** [comment]
I'd almost call this "Backstage" now

**Comment by younglisa** [comment]
@brooklynchuck what about the intro line underneath? Do you think this still stands without the "adjust sounds" piece?

**Comment by brooklynchuck** [comment]
Yeah, the while thing is wrong for copy.

I feel like it should be titled something like:
Extras
Credits
Etc.
About

And then rewrite the subhead, too. What do you think about changing settings?

Would we change the gear icon?

Sent from Outlook Mobilehttps://aka.ms/blhgte

**Comment by younglisa** [comment]
I will say sitting in User Testing people don't seem too tripped up by the gear icon, but if there is another icon readily available open to trying it out.

@Misokate  thoughts?

@brooklynchuck agree subhead should be rewritten also. Thoughts on how that should read?

**Comment by brooklynchuck** [comment]
"Share, review or learn more about the nerds who built this."

**Comment by kperusko** [comment]
Talked with @younglisa about the title for this section. The name for the page will be "Extras". And subhead will be "Share, review or learn more about the nerds who built this." as per @brooklynchuck comment.
@Misokate  do you think we should also change the icon for this page?

**Comment by Misokate** [comment]
I'll meet with Francia and see what she thinks. I don't think we should try and come up with a clever icon for that since we want the user to have an idea what they'll find... I might vote to keep it was the gear because it is still the gears behind the app itself, but I'll ask her and get back @younglisa @kperusko

**Comment by Misokate** [comment]
Spoke to Francia, let's keep it as settings for now and re assess for v2.0 when we add sounds and other extras!

@younglisa @kperusko

**Comment by younglisa** [comment]
ok - so to confirm the only change will be to the copy underneath to say:

"Share, review or learn more about the nerds who built this."

cc: @kperusko

**Comment by sshaar08** [comment]
Looking good
